<!-- DDGCompanion.csproj -->
<!-- C# Project Configuration -->
<!-- Added by Graph Technologies, 2025 -->

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>DDGCompanion</AssemblyName>
    <RootNamespace>DDGCompanion</RootNamespace>
    <Version>1.2.0</Version>
    <Authors>Graph Technologies</Authors>
    <Company>Graph Technologies</Company>
    <Product>DDG Course Companion</Product>
    <Description>Discrete Differential Geometry implementation in C#</Description>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Tests\**" />
    <Compile Remove="GeometryKit\**" />
    <EmbeddedResource Remove="GeometryKit\**" />
    <None Remove="GeometryKit\**" />
    <Compile Remove="GeometryKit.Tests\**" />
    <EmbeddedResource Remove="GeometryKit.Tests\**" />
    <None Remove="GeometryKit.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="MathNet.Numerics.MKL.Win-x64" Version="3.0.0" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
  </ItemGroup>
</Project>
